# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d4eab04fb11f21a9e5e80c2d7ad299fa8ec260c7e4b2471c023cf703842c1dd8966ae3419584e968247aef1c7ce5af971abd45d38a9db941a2600f03a7013bfd

test:
  secret_key_base: 03b58f6f0b2e9fc46b7468c6fee24139a649041075a2dcfbe3c244a03b028c5756fc09ed4db098c9a407248f35953f40156f4dfad8402d5cdf67b542b2bd0ed2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
